"""Add building column to meeting

Revision ID: b746cd9b6b41
Revises: c3592c25409c
Create Date: 2023-08-11 12:14:47.725331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b746cd9b6b41"
down_revision = "c3592c25409c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting",
        sa.Column(
            "building",
            sa.String(length=10),
            nullable=True,
            comment="Meeting building.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting", "building")
    # ### end Alembic commands ###
