"""Add batch process table

Revision ID: 28a368e5676b
Revises: f3d1f209a8fb
Create Date: 2024-03-03 10:03:36.557099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "28a368e5676b"
down_revision = "f3d1f209a8fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(sa.schema.CreateSequence(sa.Sequence("batch_process_id_seq")))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_process",
        sa.Column(
            "id",
            sa.Integer(),
            server_default=sa.text("nextval('batch_process_id_seq')"),
            nullable=False,
            comment="Serial batch process ID.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default="now()",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batch_process")),
        comment="Batch process records.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("batch_process")
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("batch_process_id_seq")))
