"""Alter course.url length

Revision ID: 317d5306c14e
Revises: 178719586e69
Create Date: 2023-09-06 16:25:52.263838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "317d5306c14e"
down_revision = "178719586e69"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "course",
        "url",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.String(length=2083),
        existing_comment="BCIT Course URL.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "course",
        "url",
        existing_type=sa.String(length=2083),
        type_=sa.VARCHAR(length=120),
        existing_comment="BCIT Course URL.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
