"""Add on delete cascade to offering.term_id

Revision ID: 83135043932d
Revises: 8a725632af56
Create Date: 2023-09-14 19:00:46.140192

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "83135043932d"
down_revision = "8a725632af56"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("offering_term_id_fkey", "offering", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_offering_term_id_term"),
        "offering",
        "term",
        ["term_id"],
        ["term_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_offering_term_id_term"), "offering", type_="foreignkey")
    op.create_foreign_key(
        "offering_term_id_fkey", "offering", "term", ["term_id"], ["term_id"]
    )
    # ### end Alembic commands ###
