"""Add subject.is_active field

Revision ID: 871389a90551
Revises: 317d5306c14e
Create Date: 2023-09-10 07:31:49.371047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "871389a90551"
down_revision = "317d5306c14e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subject",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=True,
            comment="Whether the subject is included in web scraping.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subject", "is_active")
    # ### end Alembic commands ###
