"""Unique constraint naming convention

Revision ID: d0c807fc8328
Revises: 6253c78c6b3a
Create Date: 2023-10-23 05:17:38.468355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0c807fc8328"
down_revision = "6253c78c6b3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_course_subject_id", "course", type_="unique")
    op.create_unique_constraint(
        op.f("uq_course_subject_id_code"), "course", ["subject_id", "code"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_course_subject_id_code"), "course", type_="unique")
    op.create_unique_constraint(
        "uq_course_subject_id", "course", ["subject_id", "code"]
    )
    # ### end Alembic commands ###
