"""Add soft delete

Revision ID: ee39506eab40
Revises: 83135043932d
Create Date: 2023-09-16 19:54:29.285309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee39506eab40"
down_revision = "83135043932d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "meeting",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "offering",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "subject",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "term",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "deleted_at")
    op.drop_column("term", "deleted_at")
    op.drop_column("subject", "deleted_at")
    op.drop_column("offering", "deleted_at")
    op.drop_column("meeting", "deleted_at")
    op.drop_column("course", "deleted_at")
    # ### end Alembic commands ###
